#!/bin/sh

# Installation
apt-get install logstash -y

# SSL cert&key
sudo mkdir -p /etc/pki/tls/certs
sudo mkdir /etc/pki/tls/private
sudo openssl req -config /etc/ssl/openssl.cnf -x509 -days 3650 -batch -nodes -newkey rsa:2048 -keyout /etc/pki/tls/private/logstash-forwarder.key -out /etc/pki/tls/certs/logstash-forwarder.crt

# Starter Pipeline
echo -e "input{\n\tbeats{\n\t\tport => 5044\n\t\tssl => true\n\t\tssl_certificate => '/etc/pki/tls/certs/logstash-forwarder.crt'\n\t\tssl_key => '/etc/pki/tls/private/logstash-forwarder.key'\n\t}\n}" > /etc/logstash/conf.d/beats_input.conf
echo -e "output{\n\telasticsearch{\n\t\thosts => ['localhost:9200', '127.0.0.1:9200']\n\t\tmanage_template => false\n\t\tindex => '%{[@metadata][beat]}-%{[@metadata][version]}-%{+YYYY.MM.dd}'\n\t\taction => create\n\t}\n}" > /etc/logstash/conf.d/elasticsearch_output.conf

# Service Config
# Logstash can take a very long time to shut down. This kills the process after 3 minutes of shutting down
sed -i 's/.TimeoutStopSec.*/TimeoutStopSec=180/' /etc/systemd/system/logstash.service

# Enable Service
systemctl enable logstash
