#!/bin/bash
# 
# pwd must be the ElasticStackSetup directory
#
# Process:
# - runs the setup script for each individual program
# - starts each program
# - runs the status_Elastic_services script, displaying current status of each program

CYAN='\033[1;36m'

#setup
echo -e "${CYAN}Starting setup_elasticsearch..."
bash ./setup_elasticsearch
echo -e "${CYAN}Completed setup_elasticsearch"

echo -e "${CYAN}Starting setup_kibana..."
bash ./setup_kibana
echo -e "${CYAN}Completed setup_kibana"

echo -e "${CYAN}Starting setup_logstash..."
bash ./setup_logstash
echo -e "${CYAN}Completed setup_logstash"

echo -e "${CYAN}Starting setup_filebeat..."
bash ./setup_filebeat
echo -e "${CYAN}Completed setup_filebeat"

echo -e "${CYAN}Setup Complete. Starting services"

#start

echo -e "${CYAN}Starting elasticsearch..."
systemctl start elasticsearch.service

echo -e "${CYAN}Starting kibana..."
systemctl start kibana.service

echo -e "${CYAN}Starting logstash..."
systemctl start logstash.service

echo -e "${CYAN}Starting filebeat..."
systemctl start filebeat.service

bash ./status_Elastic_services.bash

