#!/bin/sh

# Installation
apt-get install filebeat -y

# Starter Configuration
  # commenting/disabling elasticsearch output
sed -i '/output.elasticsearch:/ s/^/#/' /etc/filebeat/filebeat.yml
sed -i '/.*localhost:9200.*/ s/^/#/' /etc/filebeat/filebeat.yml

  # uncommenting/enabling logstash output
sed -i '/output.logstash:/ s/#//' /etc/filebeat/filebeat.yml
sed -i '/.*localhost:5044.*/ s/#//' /etc/filebeat/filebeat.yml

filebeat modules enable system
filebeat modules enable logstash
filebeat setup --pipelines --modules system

# Enable Service
systemctl enable filebeat
