#!/bin/bash
#
# I keep getting a 'failed to authenticate kibana_system user for REST request' error, which stops kibana from ingesting logs from elasticsearch,
# and I don't know why since I can authenticate the kibana_system user manually with no issue
#
# REMEMBER TO SAVE PASSWORDS
# must run as root & must run after setup_apt has been run

# For cyan color output
CYAN='\033[1;36m'
NC='\033[0m'

# Dependencies
apt-get install pwgen # for random password generation

sed -i '/.*xpack.security.enabled.*/ s/^#//' /etc/elasticsearch/elasticsearch.yml # enable security features on elasticsearch
echo -e "${CYAN}Restarting Elasticsearch with security features enabled${NC}"
systemctl restart elasticsearch.service # elasticsearch has to be running for the password generation to work
sleep 16 # allow elasticsearch nodes to get to green health. not the best solution but it hasn't not-worked so far

# Assign random strings to passwords
echo -e "${CYAN}Creating random passwords${NC}"
ELASTICPASS=$(pwgen 16 1) # elastic
APMPASS=$(pwgen 16 1) # apm_system
KIBANAPASS=$(pwgen 16 1) #kibana_system
LOGSTASHPASS=$(pwgen 16 1) #logstash_system
BEATSPASS=$(pwgen 16 1) #beats_system
REMOTEMONITORINGUSERPASS=$(pwgen 16 1) #remote_monitoring_user
# automatically input the generated passwords into the elasticsearch-setup-passwords script
printf '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s' ${ELASTICPASS} ${ELASTICPASS} ${APMPASS} ${APMPASS} ${KIBANAPASS} ${KIBANAPASS} ${LOGSTASHPASS} ${LOGSTASHPASS} ${BEATSPASS} ${BEATSPASS} ${REMOTEMONITORINGUSERPASS} ${REMOTEMONITORINGUSERPASS} | /usr/share/elasticsearch/bin/elasticsearch-setup-passwords interactive --batch

echo -e "${CYAN}Adding kibana_system username&password to kibana.yml and kibana-keystore${NC}"
sed -i "s/.*elasticsearch.password.*/elasticsearch.password: '$KIBANAPASS'/" /etc/kibana/kibana.yml
printf '%s' 'kibana_system' | /usr/share/kibana/bin/kibana-keystore add elasticsearch.username
printf '%s' ${KIBANAPASS} | /usr/share/kibana/bin/kibana-keystore add elasticsearch.password
chown kibana: /etc/kibana/kibana.keystore # kibana user should own the kibana.keystore and hash
chown kibana: /etc/kibana/.kibana.keystore.initial_md5sum

echo -e "${CYAN}\nRestarting Kibana with security features enabled${NC}"
systemctl restart kibana.service

echo -e "${CYAN}\nTHESE PASSWORDS ARE NOT STORED ANYWHERE. SAVE THEM SOMEPLACE SAFE${NC}"
echo -e "${CYAN}|${NC}"
echo -e "${CYAN}elastic password: ${ELASTICPASS}${NC}"
echo -e "${CYAN}kibana_system password: ${KIBANAPASS}${NC}"
echo -e "${CYAN}logstash_system password: ${LOGSTASHPASS}${NC}"
echo -e "${CYAN}beats_system password: ${BEATSPASS}${NC}"
echo -e "${CYAN}apm_system password: ${APMPASS}${NC}"
echo -e "${CYAN}remote_monitoring_user password: ${REMOTEMONITORINGUSERPASS}${NC}"
echo -e "${CYAN}|${NC}"
echo -e "${CYAN}THESE PASSWORDS ARE NOT STORED ANYWHERE. SAVE THEM SOMEPLACE SAFE${NC}"
