#!/bin/bash
#
# REMEMBER TO SAVE PASSWORDS
#
# must be run as root
# must be run after setup_install and setup_passwords have both been run
#

CYAN='\033[1;36m'
NC='\033[0m'

apt install unzip

echo -e "${CYAN}Stopping elasticsearch.service${NC}"
systemctl stop elasticsearch.service
echo -e "${CYAN}Stopping kibana.service${NC}"
systemctl stop kibana.service

echo -e "${CYAN}Generating random passwords for CA and certificate${NC}"
CAPASS=$(pwgen 16 1)
CERTIFICATEPASS=$(pwgen 16 1)
HTTPPASS=$(pwgen 16 1)
HOSTNAME=$(hostname)

echo -e "${CYAN}Creating CA and certificates${NC}"
printf '\n%s\n' ${CAPASS} | /usr/share/elasticsearch/bin/elasticsearch-certutil ca
printf '%s\n\n%s\n' ${CAPASS} ${CERTIFICATEPASS} | /usr/share/elasticsearch/bin/elasticsearch-certutil cert --ca elastic-stack-ca.p12
printf '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n\n%s\n%s\n\n%s\n%s\n%s\n%s\n\n' 'n' 'y' '/usr/share/elasticsearch/elastic-stack-ca.p12' ${CAPASS} '2y' 'y' 'node-1' ${HOSTNAME} 'y' '192.168.103.36' 'y' 'n' 'n' ${HTTPPASS} | /usr/share/elasticsearch/bin/elasticsearch-certutil http
unzip /usr/share/elasticsearch/elasticsearch-ssl-http.zip

echo -e "${CYAN}Moving certificates to /etc/elasticsearch directory${NC}"
mv /usr/share/elasticsearch/elastic-certificates.p12 /etc/elasticsearch/
chown elasticsearch: /etc/elasticsearch/elastic-certificates.p12
mv /usr/share/elasticsearch/elasticsearch/http.p12 /etc/elasticsearch/
chown elasticsearch: /etc/elasticsearch/http.p12

echo -e "${CYAN}Moving certificates to /etc/kibana directory${NC}"
mv /usr/share/elasticsearch/kibana/elasticsearch-ca.pem /etc/kibana/
chown elasticsearch: /etc/kibana/elasticsearch-ca.pem


echo -e "${CYAN}Configuring elasticsearch.yml file${NC}"
sed -i '/.*cluster.name.*/ s/^#//' /etc/elasticsearch/elasticsearch.yml
sed -i '/.*node.name.*/ s/^#//' /etc/elasticsearch/elasticsearch.yml
sed -i '/.*xpack.security.transport.ssl.enabled.*/ s/^#//' /etc/elasticsearch/elasticsearch.yml
sed -i '/.*xpack.security.transport.ssl.verification_mode.*/ s/^#//' /etc/elasticsearch/elasticsearch.yml
sed -i '/.*xpack.security.transport.ssl.client_authentication.*/ s/^#//' /etc/elasticsearch/elasticsearch.yml
sed -i '/.*xpack.security.transport.ssl.keystore.path.*/ s/^#//' /etc/elasticsearch/elasticsearch.yml
sed -i '/.*xpack.security.transport.ssl.truststore.path.*/ s/^#//' /etc/elasticsearch/elasticsearch.yml
sed -i '/.*xpack.security.http.ssl.enabled.*/ s/^#//' /etc/elasticsearch/elasticsearch.yml
sed -i '/.*xpack.security.http.ssl.keystore.path.*/ s/^#//' /etc/elasticsearch/elasticsearch.yml

echo -e "${CYAN}Configuring kibana.yml file${NC}"
sed -i 's/.elasticsearch.hosts.*/elasticsearch.hosts: https://localhost:9200/' /etc/kibana/kibana.yml
sed -i '/.*elasticsearch.ssl.certificateAuthorities.*/ s/^#//' /etc/kibana/kibana.yml

echo -e "${CYAN}Adding certificate passwords to elasticsearch-keystore${NC}"
printf '%s\n' ${CERTIFICATEPASS} | /usr/share/elasticsearch/bin/elasticsearch-keystore add xpack.security.transport.ssl.keystore.secure_password
printf '%s\n' ${CERTIFICATEPASS} | /usr/share/elasticsearch/bin/elasticsearch-keystore add xpack.security.transport.ssl.truststore.secure_password
printf '%s\n' ${HTTPPASS} | /usr/share/elasticsearch/bin/elasticsearch-keystore add xpack.security.http.ssl.keystore.secure_password

echo -e "${CYAN}\nTHESE PASSWORDS ARE NOT STORED ANYWHERE. SAVE THEM SOMEPLACE SAFE${NC}"
echo -e "${CYAN}|${NC}"
echo -e "${CYAN}certificate authority password: ${CAPASS}${NC}"
echo -e "${CYAN}certificate password: ${CERTIFICATEPASS}${NC}"
echo -e "${CYAN}HTTP certificate password: ${HTTPPASS}${NC}"
echo -e "${CYAN}|${NC}"


echo -e "${CYAN}Starting elasticsearch.service${NC}"
systemctl start elasticsearch.service
echo -e "${CYAN}Starting kibana.service${NC}"
systemctl start kibana.service


