#!/bin/sh

#installation
apt-get install curl
curl -fsSL https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" >> /etc/apt/sources.list.d/elastic-7.x.list
apt update && apt-get install elasticsearch -y

#configuration
sed -i 's/*http.port*/http.port: 9200/' /etc/elasticsearch/elasticsearch.yml
sed -i 's/*network.host*/network.host: 0.0.0.0/' /etc/elasticsearch/elasticsearch.yml
sed -i 's/*discovery.seed_hosts*/discovery.seed_hosts: ["127.0.0.1"]/' /etc/elasticsearch/elasticsearch.yml

#enabling as a service
systemctl daemon-reload
systemctl enable elasticsearch
