#!/bin/sh

# Installation
apt-get install kibana -y

# Starter Configuration
sed -i 's/.server.port.*/server.port: 5061/' /etc/kibana/kibana.yml
sed -i 's/.server.host.*/server.host: 0.0.0.0/' /etc/kibana/kibana.yml
sed -i 's/.elasticsearch.hosts.*/elasticsearch.hosts: ["localhost:9200"]/' /etc/kibana/kibana.yml
sed -i 's/.elasticsearch.username.*/elasticsearch.username: "elastic"/' /etc/kibana/kibana.yml
sed -i 's/.elasticsearch.password.*/elasticsearch.password: "changeme"/' /etc/kibana/kibana.yml

# default encryption keys. these probably should be changed so we don't all have the same keys
echo 'xpack.encryptedSavedObjects.encryptionKey: "GXlGRCx7GpnjBFXmQtbcvZpdBedJxiYy"' | tee -a /etc/kibana/kibana.yml
echo 'xpack.security.encryptionKey: "5qWdAoNqEGTSRSkjbV4Z8yi3Aro1tmYM"' | tee -a /etc/kibana/kibana.yml
echo 'xpack.reporting.encryptionKey: "lr9tH2GY2i07Ig0AtkTYCFABTXfuZGsK"' | tee -a /etc/kibana/kibana.yml


# Enable Service
systemctl enable kibana
