#!/bin/bash
#
# must run as root
# pwd must be the ElasticStackSetup directory
#
# Process:
# - runs the setup script for each individual program
# - starts each program
# - runs the status_Elastic_services script, displaying current status of each program

start_time=`date +%s`

CYAN='\033[1;36m'
NC='\033[0m'

# Setup Services

echo -e "${CYAN}Starting setup_elasticsearch...${NC}"
bash ./setup_elasticsearch
echo -e "${CYAN}Completed setup_elasticsearch${NC}"

echo -e "${CYAN}Starting setup_kibana...${NC}"
bash ./setup_kibana
echo -e "${CYAN}Completed setup_kibana${NC}"

echo -e "${CYAN}Starting setup_logstash...${NC}"
bash ./setup_logstash
echo -e "${CYAN}Completed setup_logstash${NC}"

echo -e "${CYAN}Starting setup_filebeat...${NC}"
bash ./setup_filebeat
echo -e "${CYAN}Completed setup_filebeat${NC}"

echo -e "${CYAN}Setup Complete. Starting services${NC}"

# Start Services

echo -e "${CYAN}Starting elasticsearch...${NC}"
systemctl start elasticsearch.service

echo -e "${CYAN}Starting kibana...${NC}"
systemctl start kibana.service

echo -e "${CYAN}Starting logstash...${NC}"
systemctl start logstash.service

echo -e "${CYAN}Starting filebeat...${NC}"
systemctl start filebeat.service

# Display Service Status

bash ./status_Elastic_services.bash

# Runtime Stats

end_time=`date +%s`
runtime=$((end_time-start_time))
echo -e "${CYAN}Runtime: ${runtime} seconds${NC}"
